feat: Add OAuth integration with github
oskarwilliams378/DevOps-Course-Starter pull request #10
Opened 2021-03-03 16:10 UTC by oskarwilliams378

2021-03-11 14:52 UTC, JackMead requested changes
Nice work, I had to authenticate in order to view your todos, and was unable to make changes under my github name. It looks like this hasn't yet been deployed to heroku; you may need to think about setting up a second Oauth App in Github so that your callback address is configured correctly there once that does happen

I've left a few thoughts below, but the only important thing that we should adjust here is to add some info to the README to warn developers that they'll need to register with Github, and to mention the new environment variables that they'll require

2021-03-11 14:52 UTC, JackMead commented on .travis.yml
> +  - docker run -e DB_USER -e PASSWORD -e MONGO_URL -e SECRET_KEY -e CLIENT_ID -e CLIENT_SECRET todo-app:test tests_selenium
Do we need these variables, given that the login is disabled?
We currently need some value to be set, but if they're never used we could just set default values in the test (like we do with the `DEFAULT_DATABASE`)

2021-03-11 14:52 UTC, JackMead commented on .travis.yml
> +  if: branch = master
Do we need this in addition to the `on: branch: master` below?

2021-03-11 14:52 UTC, JackMead commented on app.py
> +            return redirect('/')
In practise it would be better to actually make it clear that the user has hit a permissions error, ideally with a status code & error page

2021-03-11 14:52 UTC, JackMead commented on tests_selenium/test_app.py
> +user_with_write = User('47484139')
You flag this same number in a few places, feels like it might be better as an environment variable

2021-03-17 13:36 UTC, oskarwilliams378 commented on .travis.yml
> +  - docker run -e DB_USER -e PASSWORD -e MONGO_URL -e SECRET_KEY -e CLIENT_ID -e CLIENT_SECRET todo-app:test tests_selenium
Will add defaults

2021-03-17 13:36 UTC, oskarwilliams378 commented on .travis.yml
> +  if: branch = master
I think so

2021-03-17 13:36 UTC, oskarwilliams378 commented on app.py
> +            return redirect('/')
I agree in real practice, here I think this is fine :)

2021-03-17 13:37 UTC, oskarwilliams378 commented on tests_selenium/test_app.py
> +user_with_write = User('47484139')
Will do

2021-03-30 11:23 UTC, hugh-emerson approved these changes
Looks good. You can merge when you're ready, but you should add some more detail to the README.

The other comments are very minor.

2021-03-31 12:37 UTC, oskarwilliams378 commented on app.py
> +        login_user(User(user_id))
done

2021-03-31 12:37 UTC, oskarwilliams378 commented on app.py
> +def is_writer(user):
done

2021-03-31 12:44 UTC, oskarwilliams378 commented on README.md
> +The `CLIENT_ID` and `CLIENT_SECRET` are the GitHub OAuth App id and secret.
done

2021-03-31 12:49 UTC, merged