Exercise 11
oskarwilliams378/DevOps-Course-Starter pull request #11
Opened 2021-03-31 12:55 UTC by oskarwilliams378

2021-04-13 12:54 UTC, JackMead requested changes
Looks good, I can see the app hosted in Azure and interact with it. Your Travis pipeline is currently failing though, so we should fix that up before we merge this - see my comment below

2021-04-13 12:54 UTC, JackMead commented on helpers/mongo_wrapper.py
> +        return pymongo.MongoClient(f"mongodb://{username}:{password}@{mongo_url}/{database_name}?ssl=true&retryWrites=false&w=majority")
Here, you're tying the application quite tightly to the parameters required by the connection string (e.g. removing `+srv` has caused your tests to fail in Travis)
A better solution here would be to pull out this connection string as a single environment variable - your tests can continue to use e.g. the Atlas hosted DB, whilst Azure can use it's Cosmos DB

2021-04-21 14:33 UTC, oskarwilliams378 commented on helpers/mongo_wrapper.py
> +        return pymongo.MongoClient(f"mongodb://{username}:{password}@{mongo_url}/{database_name}?ssl=true&retryWrites=false&w=majority")
Fixed

2021-04-28 12:57 UTC, merged

2021-05-05 10:15 UTC, JackMead reviewed
Thanks for making that change, I'm happy that this is now passing in Travis, though I note your deployments aren't being picked up & we should fix that. It looks like that's an earlier change, I suspect the culprit is the `if: branch = master ` condition in your deploy lifecycle stage - we can get rid of that completely since you've already got the `on: branch: master` section.

2021-05-05 13:06 UTC, oskarwilliams378 commented
Fixed