feat: Add logging to loggly
oskarwilliams378/DevOps-Course-Starter pull request #14
Opened 2021-05-19 16:06 UTC by oskarwilliams378

Add logging to loggly

![image](https://user-images.githubusercontent.com/47484139/118846315-80dd0000-b8c4-11eb-8cf1-451a80d4b2d4.png)

2021-05-26 10:41 UTC, BenRamchandani requested changes
The logging looks good. It would be nice to log logins and user ids for actions too, but that probably covers it.

You do need to fix your travis build and the instructions for running tests in your README though and think about how you want logging in your tests to work - probably best to make `LOGGLY_TOKEN` optional and not log to loggly in your tests.

2021-05-26 10:41 UTC, BenRamchandani commented on app.py
> +    if loggly_token is not None:
`os.environ['LOGGLY_TOKEN']` will already have thrown if `LOGGLY_TOKEN` isn't in `os.environ`.

I think you want something like this, and get rid of `LOGGLY_TOKEN` in `.env.test`
```suggestion
    app.logger.setLevel(os.environ.get('LOG_LEVEL', 'DEBUG'))

    loggly_token = os.environ.get('LOGGLY_TOKEN')

    if loggly_token is not None:
```

2021-06-28 16:25 UTC, hugh-emerson approved these changes
You could also log a warning when your `writer_only` function finds someone unauthorised. People should only hit that if there's a bug or they are deliberately attempting to do something they shouldn't.

Otherwise I've just left some minor comments. Merge when you're ready 👍

2021-06-28 16:25 UTC, hugh-emerson commented on app.py
> +    if loggly_token is not None:
You could change this to also skip an empty string value:

```suggestion
    if loggly_token:
```

2021-06-28 16:25 UTC, hugh-emerson commented on README.md
> +In order to log with Loggly, add the `LOGGLY_TOKEN` environment variable, which is the customer token for the Loggly logging found [here](https://oskarwilliams.loggly.com/tokens).
That link looks a little specific to you.

2021-06-28 16:25 UTC, hugh-emerson commented on variables.tf
> +  description = "The customer token for the loggly account"
Variables can have a `sensitive = true`, like outputs, to ensure they don't get included in any logs

2021-07-14 15:32 UTC, merged