Add Vagrantfile and pyproject.toml but haven't tested due to machine issues
oskarwilliams378/DevOps-Course-Starter pull request #4
Opened 2020-08-19 15:39 UTC by oskarwilliams378

2020-08-26 15:38 UTC, hugh-emerson requested changes
Do you find a fresh `vagrant up` works without errors and you're able to access the site from your host machine? Do `vagrant destroy` first, in case there is any snowflaked config.

I find it fails for a couple of reasons:
- the python 3 installation is unsuccessful (hint: your first provisioning script is running as root)
- `poetry install` followed by `poetry run flask run` doesn't work because you haven't added your dependencies to poetry

Also you should update the README to mention the option of running it in vagrant.

2020-08-26 15:38 UTC, hugh-emerson commented on Vagrantfile
> +            poetry run flask run --host=0.0.0.0
It would be nice to run it as a background task so that the vagrant up completes.

2020-08-26 15:38 UTC, hugh-emerson commented on Vagrantfile
> +        source $HOME/.poetry/env
What is the purpose of this line?

2020-08-26 15:38 UTC, hugh-emerson commented on Vagrantfile
> +            exec "$SHELL"
Does this do anything since it's at the end of this shell script?

If you want to have commands below this that take advantage of the changed `.profile`, can you `source` it instead?

2020-08-26 15:38 UTC, hugh-emerson commented on pyproject.toml
> +
I expect this to contain all of your dependencies. 
E.g.
```
python = "^3.7"
flask = "^1.1.2"
python-dotenv = "^0.14.0"
requests = "^2.24.0"
```

2020-08-26 15:42 UTC, hugh-emerson commented
It wasn't part of the exercise brief but since it got you to set up poetry you could consider ditching venv/pip (i.e. delete requirements.txt and the setup scripts and always use poetry). If you do you should update the README accordingly.

2020-09-02 09:33 UTC, oskarwilliams378 commented on pyproject.toml
> +
Done

2020-09-02 14:49 UTC, oskarwilliams378 commented on Vagrantfile
> +        source $HOME/.poetry/env
pass

2020-09-02 14:49 UTC, oskarwilliams378 commented on Vagrantfile
> +            exec "$SHELL"
Have combined the 2 sections

2020-09-02 14:49 UTC, oskarwilliams378 commented on pyproject.toml
> +
Done

2020-09-02 14:49 UTC, oskarwilliams378 commented on Vagrantfile
> +    config.vm.network "forwarded_port", guest: 5000, host: 5001
This is a personal quirk as I like not having to worry about colliding ports at all

2020-09-09 15:58 UTC, merged

2020-09-11 12:56 UTC, hugh-emerson reviewed
Two more small comments but otherwise looks good :+1:

2020-09-11 12:56 UTC, hugh-emerson commented on pyproject.toml
> +selenium = "^3.141.0"
You should not include everything from pip freeze in here. Only include things you explicitly installed (and flask and python-dotenv which were already included in the starter project)

Also, it's better to put packages like pytest and selenium into the dev-dependencies section.

2020-09-11 12:56 UTC, hugh-emerson commented on README.md
> +The project uses a poetry to isolate package dependencies. To create the virtual environment and install required packages, run the following from a bash shell terminal:
You should also include a line saying to copy .env.template to .env during first time setup (it was done in setup.sh)