feat: Add travis file and docker-compose test
oskarwilliams378/DevOps-Course-Starter pull request #7
Opened 2020-11-11 16:47 UTC by oskarwilliams378

2020-11-26 16:58 UTC, hugh-emerson requested changes
I can't see your Travis output, but it doesn't look to me like your selenium tests would run successfully?

Also, there's no need to delete .dockerignore! You could change the `.env*` line to `.env` so that .env.test gets copied into the test image, and remove the test folders from it.

2020-11-26 16:58 UTC, hugh-emerson commented on tests_selenium/conftest.py
> +#         yield driver
Delete commented out code

2020-11-26 16:58 UTC, hugh-emerson commented on .travis.yml
> +before_install:
Should be `script` rather than `before_install`

Sections like `before_install` and `install` are for dividing your commands into semantically different sections, like installing dependencies before actually running your build/tests

2020-11-26 16:58 UTC, hugh-emerson commented on Dockerfile
> +RUN ls
This should be after installing Chrome and webdriver so you don't need to rebuild as much after changing code.

2020-12-02 13:50 UTC, oskarwilliams378 commented on tests_selenium/conftest.py
> +#         yield driver
Done

2020-12-02 13:51 UTC, oskarwilliams378 commented on .travis.yml
> +before_install:
Ahhh ok

2020-12-02 13:51 UTC, oskarwilliams378 commented on Dockerfile
> +RUN ls
Doh that was debugging stuff

2020-12-02 13:59 UTC, oskarwilliams378 commented
Not sure how to reply to your head comment @hugh-emerson, but the reason I removed the gitignore is becuase I also need to copy the tests folders, should I just remove the tests fodlers from the dockerignore?

Also all the test work

2020-12-02 14:00 UTC, oskarwilliams378 commented on .travis.yml
> + - TRELLO_KEY=dummy_key TRELLO_TOKEN=dummy_token FLASK_SKIP_DOTENV=true
The tests all work. I'm not sure what you mean about e2e not working without real credentials thouogh, the selenium tests use a mocked trello

2020-12-09 16:12 UTC, merged

2020-12-23 13:36 UTC, hugh-emerson reviewed
Travis config looks good now 👍

2020-12-23 13:36 UTC, hugh-emerson commented on exercise-8.md
> +# Module 8 Project Exercise
This file shouldn't be committed. And you should hopefully have the pdf now.

2020-12-23 14:33 UTC, oskarwilliams378 commented on exercise-8.md
> +# Module 8 Project Exercise
Not sure how it did, will delete in next PR