Exercise 8
oskarwilliams378/DevOps-Course-Starter pull request #8
Opened 2020-12-09 16:16 UTC by oskarwilliams378

2021-01-06 09:55 UTC, Jonesey13 requested changes
This is very nearly there but the production container currently does not work locally (as described in the README). Technically speaking the deploy is also broken at the moment (see the comment below).

There are also a couple more minor comments below.

2021-01-06 09:55 UTC, Jonesey13 commented on .travis.yml
>    - secure: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCosJY7wC/4ijdzaj3NP7bYbOrgfXLWlqbm7Xq43WmZOxbjLLA0nmQh0wTism2MAf7E4DyscJTzF6AMQdphKgUiN5HwgEIgSEKrDl6VcXZWEjqDV1+FMWwp504r8rlPj6ly1H2zKcTQA4F2SXXiXwu
What does this environment variable refer to? (this feels like something that should be mentioned in the README)

Also on Travis you have a bunch of env variables set:
![image](https://user-images.githubusercontent.com/8018173/103753746-54a2a000-5003-11eb-9a75-6b42cf362c89.png)
Should these perhaps be here?

2021-01-06 09:55 UTC, Jonesey13 commented on .travis.yml
> +  - docker build --target test --tag todo-app:test .
This actually breaks atm due to the lack of a docker login and docker hub rate limiting: https://travis-ci.com/github/oskarwilliams378/DevOps-Course-Starter/builds/207511188

2021-01-06 09:55 UTC, Jonesey13 commented on Dockerfile
> +ENTRYPOINT "poetry run gunicorn 'app:create_app()' --bind 0.0.0.0:$PORT"
This breaks the production container README instructions locally:
![image](https://user-images.githubusercontent.com/8018173/103754806-c2030080-5004-11eb-893e-f6bcb4f791fc.png)
Also you should be using exec syntax like you were before (if you're needing to insert an environment variable defer to a shell script).

This currently prevent this submission from passing review.

2021-01-13 13:56 UTC, oskarwilliams378 commented on .travis.yml
> +  - docker build --target test --tag todo-app:test .
that wasn't failing for me which is very interesting

2021-01-13 14:01 UTC, oskarwilliams378 commented on .travis.yml
>    - secure: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCosJY7wC/4ijdzaj3NP7bYbOrgfXLWlqbm7Xq43WmZOxbjLLA0nmQh0wTism2MAf7E4DyscJTzF6AMQdphKgUiN5HwgEIgSEKrDl6VcXZWEjqDV1+FMWwp504r8rlPj6ly1H2zKcTQA4F2SXXiXwu
I will add to the README

So those env variables get added by using the env secure

2021-01-13 14:02 UTC, oskarwilliams378 commented on .travis.yml
> +  - docker build --target test --tag todo-app:test .
So this seems to occasionally fail, but due to the pulling of requisite images, what is a way around that?

2021-01-13 14:22 UTC, oskarwilliams378 commented on .travis.yml
> +  - docker build --target test --tag todo-app:test .
Unless are you saying that logging in would prevent the hub rate limiting?

2021-01-13 14:22 UTC, oskarwilliams378 commented on Dockerfile
> +ENTRYPOINT "poetry run gunicorn 'app:create_app()' --bind 0.0.0.0:$PORT"
Not exactly sure what you mean here about the using exec syntax, I haven't done that

2021-01-13 14:59 UTC, oskarwilliams378 commented on Dockerfile
> +ENTRYPOINT "poetry run gunicorn 'app:create_app()' --bind 0.0.0.0:$PORT"
Fixed

2021-01-13 14:59 UTC, oskarwilliams378 commented on .travis.yml
> +  - docker build --target test --tag todo-app:test .
Fixed

2021-01-28 12:36 UTC, JackMead requested changes
Looks like most changes are fixed, but your docker-compose instructions are still out of date for local prod builds. I've left a few other thoughts on the PR that would be worth looking at

2021-01-28 12:36 UTC, JackMead commented on .travis.yml
> +  - docker build --target prod --tag oskwil/todo-app:$TRAVIS_COMMIT .
If I follow, you've switched off travis builds on PRs so this stage does only run on main, but it means your tests are no longer running against PRs - it would be nice to switch those back on, and maybe move this step to a before_deploy stage so that you're not pushing images from non-main branches

2021-01-28 12:36 UTC, JackMead commented on entrypoint.sh
> +poetry run gunicorn 'app:create_app()' --bind 0.0.0.0:"$PORT"
Nice to move this out, but I'm still unable to run the prod container locally following the instructions because the $PORT variable hasn't been set - you should be able to either set a default in the dockerfile using ENV, or specify it in your docker compose file

2021-01-28 12:36 UTC, JackMead commented on deploy.sh
> +docker pull oskwil/todo-app
Not an issue, but I'd expect this docker pull to never do anything since you just pushed the same image (and indeed in Travis it just reports that you're up to date)

2021-01-28 12:36 UTC, JackMead commented on .travis.yml
>    - secure: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCosJY7wC/4ijdzaj3NP7bYbOrgfXLWlqbm7Xq43WmZOxbjLLA0nmQh0wTism2MAf7E4DyscJTzF6AMQdphKgUiN5HwgEIgSEKrDl6VcXZWEjqDV1+FMWwp504r8rlPj6ly1H2zKcTQA4F2SXXiXwu
I'm not sure if you actually need the SSH key to access the variables set via the travis UI (which isn't in itself an issue) - the more common alternative is to encrypt the various environment variables with the travis CLI and store them directly in the .yml file, but happy that you've documented they'd need updating in Travis directly

2021-02-03 13:58 UTC, oskarwilliams378 commented on .travis.yml
>    - secure: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCosJY7wC/4ijdzaj3NP7bYbOrgfXLWlqbm7Xq43WmZOxbjLLA0nmQh0wTism2MAf7E4DyscJTzF6AMQdphKgUiN5HwgEIgSEKrDl6VcXZWEjqDV1+FMWwp504r8rlPj6ly1H2zKcTQA4F2SXXiXwu
I prefer the SSH approach as then I can change my variables in travis easily

2021-02-03 13:59 UTC, oskarwilliams378 commented on entrypoint.sh
> +poetry run gunicorn 'app:create_app()' --bind 0.0.0.0:"$PORT"
added to the template file!

2021-02-03 14:01 UTC, oskarwilliams378 commented on deploy.sh
> +docker pull oskwil/todo-app
Removed

2021-02-03 15:13 UTC, oskarwilliams378 commented on .travis.yml
> +  - docker build --target prod --tag oskwil/todo-app:$TRAVIS_COMMIT .
Done

2021-02-11 11:56 UTC, JackMead commented
Nice, that's working locally for me and deploying happily, happy for you to merge this when ready

2021-02-12 15:41 UTC, merged